version: 2

before:
  hooks:
    - go mod download
builds:
  - id: default
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    ldflags: 
      - -s
      - -w
      - "-X github.com/fmotalleb/go-tools/git.Version={{.Version}}"
      - "-X github.com/fmotalleb/go-tools/git.Commit={{.ShortCommit}}"
      - "-X github.com/fmotalleb/go-tools/git.Date={{.Date}}"
      - "-X github.com/fmotalleb/go-tools/git.Branch={{.Branch}}"
    goarch:
      - amd64

  - id: slim
    goos:
      - linux
    goarch:
      - amd64
    ldflags: 
      - -s
      - -w
      - "-X github.com/fmotalleb/go-tools/git.Version={{.Version}}"
      - "-X github.com/fmotalleb/go-tools/git.Commit={{.ShortCommit}}"
      - "-X github.com/fmotalleb/go-tools/git.Date={{.Date}}"
      - "-X github.com/fmotalleb/go-tools/git.Branch={{.Branch}}"
    binary: crontab-go
    skip: "archive"
  - id: static
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags: 
      - -s
      - -w
      - "-X github.com/fmotalleb/go-tools/git.Version={{.Version}}"
      - "-X github.com/fmotalleb/go-tools/git.Commit={{.ShortCommit}}"
      - "-X github.com/fmotalleb/go-tools/git.Date={{.Date}}"
      - "-X github.com/fmotalleb/go-tools/git.Branch={{.Branch}}"
      - "-extldflags '-static'"
    binary: crontab-go
    skip: "archive"

dockers:
  - image_templates:
      - "ghcr.io/fmotalleb/crontab-go:{{ .Version }}-static"
      - "ghcr.io/fmotalleb/crontab-go:latest-static"
    dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    ids:
      - static
    build_flag_templates:
      - "--target=static"
    use: buildx

  - image_templates:
      - "ghcr.io/fmotalleb/crontab-go:{{ .Version }}-slim"
      - "ghcr.io/fmotalleb/crontab-go:latest-slim"
    dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    ids:
      - slim
    build_flag_templates:
      - "--target=slim"
    use: buildx

archives:
  - id: default
    builds:
      - default

release:
  github:
    owner: fmotalleb
    name: crontab-go
  name_template: "{{.Version}}"
  prerelease: auto
  mode: append

changelog:
  disable: true
