version: 2

before:
  hooks:
    - go mod download
builds:
  - id: default
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags: 
      - -s
      - -w
      - "-X github.com/fmotalleb/go-tools/git.Version={{.Version}}"
      - "-X github.com/fmotalleb/go-tools/git.Commit={{.ShortCommit}}"
      - "-X github.com/fmotalleb/go-tools/git.Date={{.Date}}"
      - "-X github.com/fmotalleb/go-tools/git.Branch={{.Branch}}"

  - id: slim
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags: 
      - -s
      - -w
      - "-X github.com/fmotalleb/go-tools/git.Version={{.Version}}"
      - "-X github.com/fmotalleb/go-tools/git.Commit={{.ShortCommit}}"
      - "-X github.com/fmotalleb/go-tools/git.Date={{.Date}}"
      - "-X github.com/fmotalleb/go-tools/git.Branch={{.Branch}}"
    binary: crontab-go
    skip: "archive"
  - id: static
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags: 
      - -s
      - -w
      - "-X github.com/fmotalleb/go-tools/git.Version={{.Version}}"
      - "-X github.com/fmotalleb/go-tools/git.Commit={{.ShortCommit}}"
      - "-X github.com/fmotalleb/go-tools/git.Date={{.Date}}"
      - "-X github.com/fmotalleb/go-tools/git.Branch={{.Branch}}"
      - "-extldflags '-static'"
    binary: crontab-go
    skip: "archive"

dockers_v2:
  - id: slim
    sbom: false
    platforms:
      - linux/amd64
      - darwin/amd64
      - darwin/arm64
    images:
      - ghcr.io/fmotalleb/crontab-go
    tags:
      - "{{ .Version }}"
      - latest
    labels:
      "org.opencontainers.image.description": "Crontab-go"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
    ids:
      - slim
    flags:
      - --target=slim

  - id: distroless
    sbom: false
    platforms:
      - linux/amd64
    images:
      - ghcr.io/fmotalleb/crontab-go
    tags:
      - "{{ .Version }}-distroless"
      - latest-distroless
    labels:
      "org.opencontainers.image.description": "Crontab-go"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
    ids:
      - static
    flags:
      - --target=distroless


release:
  github:
    owner: fmotalleb
    name: crontab-go
  name_template: "{{.Version}}"
  prerelease: auto
  mode: append

changelog:
  disable: true
