before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
archives:
  - format_overrides:
      - goos: windows
        format: zip

release:
  github:
  name_template: "{{.Version}}"
  prerelease: auto
  mode: append
changelog:
  skip: true
