# yaml-language-server: $schema=schema.json
#TODO: unix/tcp socket controller
#TODO: prometheus exporter

jobs:
  - name: Test Job
    tasks:
      - command: ip a -pt
        retries: 5
        retry-delay: 5s
    schedulers:
      - on-init: true
      - interval: 10m10s
