# yaml-language-server: $schema=https://raw.githubusercontent.com/FMotalleb/crontab-go/main/schema.json

jobs:
  - name: Test Job
    description: Sample of a single job
    tasks:
      - command: echo $(whoami)
        retries: 3
        retry-delay: 1s
        timeout: 15s
        user: root
    events:
      - on-init: true
      - cron: "@yearly"
      - interval: 10m10s
    hooks:
      done:
        - command: echo Ok
      failed:
        - command: echo Failed
