# yaml-language-server: $schema=schema.json
#TODO: unix/tcp socket controller
#TODO: prometheus exporter

jobs:
  - name: Test Job
    tasks:
      - command: echo 1
        retry-delay: 5s
        # connections:
        #   - image: docker-mysql-database-phpmyadmin
        #     volumes:
        #       - "/home/motalleb/Downloads:/var/local/test"
        # env:
        #   SHELL: /bin/bash
    events:
      - on-init: true
      - web-event: test
