#TODO: unix/tcp socket controller
#TODO: prometheus exporter

jobs:
  - name: backup-database
    description: Backup the production database
    enabled: true
    tasks:
      - command: /app/backup.sh
    scheduler:
      cron: "0 0 2 * * *"
    retries: 3
    retry-delay: 123s
    hooks:
      done:
        - post: http://google.com/
          headers:
            test: test2
      failed:
        - post: http://google.com/
          headers:
            test: test2
    env:
      DB_HOST: 10.0.0.5
      DB_USER: myuser
      DB_PASS: mypassword
    metadata:
      owner: john.doe@company.com
      team: database-team

  - name: cleanup-logs
    description: Clean up old log files
    enabled: true
    tasks:
      command: /app/cleanup.sh
    scheduler:
      interval: 1h # Run every hour
    retries: 1
    metadata:
      owner: jane.smith@company.com
      team: devops-team
