#TODO: unix/tcp socket controller
#TODO: prometheus exporter

jobs:
  - name: backup-database
    description: Backup the production database
    enabled: true
    exe:
      - command: /app/backup.sh
        args: ["--help"]
    scheduler:
      cron: "0 0 2 * * *"
    retries: 3
    retry-delay: 123s
    hooks:
      pre-run:
        webhooks:
          - address: http://google.com/
            headers:
              test: test1
      done:
        webhooks:
          - address: http://google.com/
            headers:
              test: test2
      failed:
        webhooks:
          - address: http://google.com/
            headers:
              test: test3
            data:
              - job: $job
              - time: $time
              - command: $exe"
    env:
      DB_HOST: 10.0.0.5
      DB_USER: myuser
      DB_PASS: mypassword
    metadata:
      owner: john.doe@company.com
      team: database-team

  - name: cleanup-logs
    description: Clean up old log files
    enabled: true
    exe:
      command: /app/cleanup.sh
    scheduler:
      interval: 1h # Run every hour
    retries: 1
    hooks:
      pre-run:
        webhooks:
          - address: http://google.com/
            headers:
              test: test1
      done:
        webhooks:
          - address: http://google.com/
            headers:
              test: test2
      failed:
        webhooks:
          - address: http://google.com/
            headers:
              test: test3
    metadata:
      owner: jane.smith@company.com
      team: devops-team
