# yaml-language-server: $schema=schema.json
#TODO: unix/tcp socket controller
#TODO: prometheus exporter

jobs:
  - name: Test Job
    tasks:
      - command: php -v
        retry-delay: 5s
        connections:
          - container: alp
        env:
          SHELL: /bin/bash
    schedulers:
      - on-init: true
      - interval: 10m10s
