# yaml-language-server: $schema=schema.json

jobs:
  - name: echo
    tasks:
      - command: |
          echo "env: {{ env "COLE" }}"
        env:
          SHELL: /bin/sh
          COLE: test
        connections:
          - image: "library/alpine"

    events:
      # - cron: "0 * * * * *"
      # - interval: 5s
      - on-init: true
      # - web-event: test
      # - docker:
      #     image: nginx
