# yaml-language-server: $schema=schema.json
#TODO: unix/tcp socket controller
#TODO: prometheus exporter

jobs:
  - name: Test Job
    tasks:
      - command: /bin/ps
        retry-delay: 5s
        retries: 0
        connections:
          # - container: 614674b79a1b
          #     volumes:
          #       - "/home/motalleb/Downloads:/var/local/test"
          - image: alpine
        env:
          SHELL: /bin/sh
          SHELL_ARGS: "-c"
    events:
      - on-init: true
      # - interval: 1s
      - web-event: test
      - web-event: test
      - web-event: test
