#TODO: unix/tcp socket controller
#TODO: prometheus exporter

jobs:
  - name: backup-database
    description: Backup the production database
    enabled: true
    tasks:
      - command: echo 15
        retries: 3
        retry-delay: 123s
        timeout: 15s
        env:
          DB_HOST: 10.0.0.5
          DB_USER: myuser
          DB_PASS: mypassword
    schedulers:
      - cron: "* * * * * *"
      - interval: 1s
      - at: 2024/05/15
    hooks:
      done:
        - post: http://google.com/
          headers:
            test: test2
      failed:
        - post: http://google.com/
          headers:
            test: test2
