# yaml-language-server: $schema=schema.json

jobs:
  - name: echo
    tasks:
      - command: env
        env:
          "COLE": test
    events:
      - log-file: /home/motalleb/Documents/GitHub/crontab-go/test
        log-check-cycle: 1s
        log-matcher: match
