#TODO: unix/tcp socket controller
#TODO: prometheus exporter

jobs:
  - name: backup-database
    description: Backup the production database
    enabled: true
    tasks:
      - command: /app/backup.sh
        retries: 3
        retry-delay: 123s
        env:
          DB_HOST: 10.0.0.5
          DB_USER: myuser
          DB_PASS: mypassword
    scheduler:
      cron: "0 0 2 * * *"

    hooks:
      done:
        - post: http://google.com/
          headers:
            test: test2
      failed:
        - post: http://google.com/
          headers:
            test: test2

  - name: cleanup-logs
    description: Clean up old log files
    enabled: true
    tasks:
      - command: /app/cleanup.sh
        retries: 1
    scheduler:
      interval: 1h # Run every hour

