#TODO: unix/tcp socket controller
#TODO: prometheus exporter

jobs:
  - name: backup-database
    description: Backup the production database
    enabled: true
    tasks:
      - command: pwd --greg
        retries: 3
        retry-delay: 1s
        timeout: 15s
        env:
          DB_HOST: 10.0.0.5
          DB_USER: myuser
          DB_PASS: mypassword
    schedulers:
      - cron: "* * * * * *"
      - interval: 1s
      # - at: 2024/05/15
    hooks:
      done:
        - command: echo Ok
      failed:
        - command: echo Failed
