# yaml-language-server: $schema=schema.json

jobs:
  - name: echo
    tasks:
      - command: echo "received"
    events:
      - on-init: true
      - docker:
          connection: unix:///var/run/docker.sock
          name: "^alpine"
          image: "^alpine.*"
          actions:
            - start
